#
# Splunk app configuration file
#

[install]
is_configured = 0

[id]
name = v2_punchcard_visualisation
version = 1.5.0

[ui]
is_visible = 1
label = v2-Punchcard-visualisation

[launcher]
author = adamliq
description = This custom visualization app contains a Punchcard. Punchcards can visualize cyclical trends in your data. This visualization shows circles representing a metric aggregated over two dimensions, such as hours of the day and days of the week. Using a punchcard, you can see relative values for a metric where the dimensions intersect.
version = 1.5.0

[package]
id = v2_punchcard_visualisation
check_for_updates = true
