[default]
display.visualizations.custom.v2_punchcard_visualisation.punchcard.radiusScale = local
display.visualizations.custom.v2_punchcard_visualisation.punchcard.useColors = false 
display.visualizations.custom.v2_punchcard_visualisation.punchcard.colorMode = categorical
display.visualizations.custom.v2_punchcard_visualisation.punchcard.minColor = #d93f3c
display.visualizations.custom.v2_punchcard_visualisation.punchcard.maxColor = #3fc77a
display.visualizations.custom.v2_punchcard_visualisation.punchcard.numOfBins = 6
display.visualizations.custom.v2_punchcard_visualisation.punchcard.labelRotation = horizontal